version: '3'

services:
  slicer:
    image: gnasello/slicer-env:2023-01-25
    build: .
    ports:
      - $GUIPORT:8080
    volumes:
      - $HOME_RESEARCHER:/home/researcher/mounted_volume # change the path before ":" with the volume you want to mount
    working_dir: /home/researcher
    environment:
       - GUIPORT=${GUIPORT}
       - HOME_RESEARCHER=${HOME_RESEARCHER}
